name: Deployment Workflow with Manual Approval

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the application
        run: echo "Building the application..."

      - name: Prepare for deployment
        run: echo "Preparing for deployment..."

    environment: staging

  post-approval:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy the application
        run: echo "Deploying the application..."

      - name: Post-deployment checks
        run: echo "Running post-deployment checks..."
