name: Deployment Workflow with Manual Approval

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the application
        run: echo "Building the application..."

      - name: Prepare for deployment
        run: echo "Preparing for deployment..."

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: 'Deploying v1.3.5 to prod from staging'
          issue-body: 'Please approve or deny the deployment of version v1.3.5.'
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
